name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Fetch Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        env:
          BASE_URL: '/'
        run: yarn build

      # cloudflare assumes if you don't have a 404.html that you are a SPA
      - name: remove 404.html
        run: rm dist/404.html

      - name: Deploy to Cloudflare
        if: github.event_name == 'push'
        uses: cloudflare/pages-action@v1
        with:
          accountId: 38542b72de6483a07c984652797f04e1
          projectName: cdda-guide
          directory: dist
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
